#%RAML 0.8
title: issue 104
version: 1.0
baseUri: http://localhost:8081/api
mediaType: application/json
traits:
  - error:
        responses:
          400:
            body:
              schema: |
                    { "$schema": "http://json-schema.org/schema",
                      "type": "object",
                      "properties": {
                        "code": { "type": "string", "required" : "true" },
                        "message": { "type": "string", "required" : "true" }
                      }
                    }
  - success:
        responses:
          200:
            body:
              schema: |
                    { "$schema": "http://json-schema.org/schema",
                      "type": "object",
                      "description": "a contact",
                      "properties": {
                        "name": { "type": "string", "required" : "true" },
                        "email": { "type": "string", "required" : "true" },
                        "phone": { "type": "string", "required" : "true" }
                      }
                    }
/contacts:
  get:
    is: [success]
  /{id}:
    get:
      is: [error]
/test:
  get:
    is: [success, error]